package com.desafio_profissional.ubs.models.domain.enums;

public enum ExameEnum {
    EXAMES_DE_SANGUE,
    EXAMES_DE_IMAGEM,
    TOMOGRAFIA_COMPUTADORIZADA,
    RESSONANCIA_MAGNETICA,
    MAMOGRAFIA,
    COLONOSCOPIA,
    ENDOSCOPIA,
    ELETROCARDIOGRAMA,
    ECOCARDIOGRAMA,
    TESTES_DE_FUNCAO_PULMONAR,
    EXAMES_DE_AUDIOMETRIA,
    EXAMES_DE_OFTALMOLOGIA,
    EXAMES_DE_DENSITOMETRIA_OSSEA,
    TESTES_DE_HIV,
    EXAMES_PARA_DIAGNOSTICO_DE_DSTS,
    EXAMES_PARA_DIAGNOSTICO_DE_HEPATITES,
    EXAMES_DE_LABORATORIO_PARA_DIAGNOSTICO_DE_CANCER,
    EXAMES_DE_URINA_E_FEZES,
    EXAMES_DE_CITOLOGIA_CERVICAL,
    EXAMES_PARA_CONTROLE_DE_DOENCAS_CRONICAS;

    ExameEnum() {
    }

}
